CREATE TABLE USER_PROFILE
(
    EMPLOYEE_ID         INT NOT NULL AUTO_INCREMENT,
    ROLE                VARCHAR(20) NOT NULL,
    DIVISION            VARCHAR(100) NOT NULL,
    PASSWORD            VARCHAR(1000) NOT NULL,
    FIRST_NAME          VARCHAR(30) NOT NULL,
    LAST_NAME           VARCHAR(20) NOT NULL,
    EMAIL               VARCHAR(50) NOT NULL,
    NID                 VARCHAR(10) NOT NULL,
    ACCOUNT_NO          VARCHAR(11) NOT NULL,
	PRESENT_ADDR_DESC   VARCHAR(1000) NOT NULL,
    PRESENT_THANA       VARCHAR(50) NOT NULL,
    PRESENT_DIST        VARCHAR(50) NOT NULL,
    PRESENT_DIV         VARCHAR(50) NOT NULL,
    PARMANENT_ADDR_DESC VARCHAR(50) NOT NULL,
    PARMANENT_THANA     VARCHAR(50) NOT NULL,
    PARMANENT_DIST      VARCHAR(50) NOT NULL,
    PARMANENT_DIV       VARCHAR(50) NOT NULL,
    DATE_OF_BIRTH       DATE NOT NULL,
    GENDER              VARCHAR(50) NOT NULL,
    RELIGION            VARCHAR(50) NOT NULL,
    MARITAL_STATUS      VARCHAR(50) NOT NULL,
    FATHER_NAME         VARCHAR(50) NOT NULL,
    MOTHER_NAME         VARCHAR(50) NOT NULL,
    SPOUSE_NAME         VARCHAR(50) NOT NULL,
    CONTACT_NO_1        VARCHAR(10) NOT NULL,
    CONTACT_NO_2        VARCHAR(10) NOT NULL,
    FACEBOOK_URL        VARCHAR(100),
    LINKEDIN_URL        VARCHAR(100),
    IMAGE               BLOB,
    PRIMARY KEY (EMPLOYEE_ID)
) AUTO_INCREMENT = 100001;


CREATE TABLE INTERN
(
    EMPLOYEE_ID     INT NOT NULL,
    UNIVERSITY      VARCHAR(100),
    CV              BLOB,
    CURRENT_STATUS	VARCHAR(50),
    START_DATE	    DATE,
    DURATION	    INT,
    END_DATE	    DATE,
    SUPERVISOR	    INT,
    ROUTINE	        BLOB,
    CERTIFICATE     TINYINT,
    PRIMARY KEY (EMPLOYEE_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES USER_PROFILE(EMPLOYEE_ID)
);
